server:
  port: 8891
  servlet:
    context-path: /zchat

# 数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://124.222.21.183:3308/leili?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 124.222.21.183
    port: 6379
    timeout: 50s
  lettuce:
    pool:
      max-idle: 50
      min-idle: 10
      max-active: 100
      max-wait: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:com/zhongger/zchat/mapper/*Mapper.xml
  #config-location: classpath:mybatis-config1.xml
  typeAliasesPackage: com.zhongger.zchat.pojo
  configuration:
    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      zhongger:
        zchat:
          mapper: debug
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count

#NameServer地址 rocketmq.name-server=192.168.232.128:9876 #默认的消息生产者组 rocketmq.producer.group=springBootGrou
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: MyConsumerGroup